import { useEffect, useState } from 'react';
import { arn, fmt } from './api';
import { useLab, PageHeader, Panel, Badge, Note, Field, KV, Tabs, Empty, DataTable, JsonEditor, Link, Modal } from './ui';

export const useInspect = (key: string | null) => { const { inspect } = useLab(); useEffect(() => { if (key) inspect(key); }, [key]); };
export const ReportBtn = ({ resource }: { resource: string }) => { const { reportFinding, status } = useLab(); return <button className="btn" disabled={status.complete} onClick={() => reportFinding(resource)}>Report finding</button>; };
export const Result = ({ r }: { r: any }) => r ? <Note tone={r.ok === false ? 'bad' : (r.result?.allowed ?? r.result?.ok ?? r.result?.recorded ?? r.result?.accepted ?? r.result?.delivered ?? true) ? 'ok' : 'warn'}><b>Result.</b> {r.message}</Note> : null;
const short = (a: string) => a.split('/').pop();
export const principals = (cloud: any) => [...Object.values<any>(cloud.iam.users).map(u => ({ arn: u.arn, label: `user/${u.name}` })), ...Object.values<any>(cloud.iam.roles).map(r => ({ arn: r.arn, label: `role/${r.name}` }))];
const attachedTo = (cloud: any, pid: string) => [...Object.values<any>(cloud.iam.users).filter(u => u.policies.includes(pid)).map(u => ({ kind: 'user', name: u.name })), ...Object.values<any>(cloud.iam.roles).filter(r => r.policies.includes(pid)).map(r => ({ kind: 'role', name: r.name }))];

// ============================== IAM ==============================
export function IamConsole() {
  const { route, nav, cloud } = useLab(); const t = route.type || 'users';
  if (t === 'user' && cloud.iam.users[route.id]) return <IamUser u={cloud.iam.users[route.id]} />;
  if (t === 'role' && cloud.iam.roles[route.id]) return <IamRole r={cloud.iam.roles[route.id]} />;
  if (t === 'policy' && cloud.iam.policies[route.id]) return <IamPolicy id={route.id} p={cloud.iam.policies[route.id]} />;
  const list = ['users', 'roles', 'policies', 'simulator'].includes(t) ? t : 'users';
  return <div className="page"><PageHeader crumbs={[{ label: 'IAM' }]} title="Identity and Access Management" desc="Identities, the policies attached to them, and what those policies allow. IAM is a global service." />
    <Tabs value={list} onChange={x => nav({ service: 'iam', type: x })} tabs={[{ id: 'users', label: `Users (${Object.keys(cloud.iam.users).length})` }, { id: 'roles', label: `Roles (${Object.keys(cloud.iam.roles).length})` }, { id: 'policies', label: `Policies (${Object.keys(cloud.iam.policies).length})` }, { id: 'simulator', label: 'Policy simulator' }]} />
    {list === 'users' && <Panel pad={false}><DataTable rows={Object.values(cloud.iam.users)} rowKey={r => r.name} onRow={r => nav({ service: 'iam', type: 'user', id: r.name })} placeholder="Find users" cols={[{ key: 'name', label: 'User name', render: r => <Link to={{ service: 'iam', type: 'user', id: r.name }}>{r.name}</Link> }, { key: 'groups', label: 'Groups', render: r => r.groups.join(', ') || '—' }, { key: 'mfa', label: 'MFA', render: r => r.mfa ? 'Enabled' : 'Not enabled' }, { key: 'console', label: 'Console access', render: r => r.console ? 'Enabled' : 'Disabled' }, { key: 'keys', label: 'Access keys', render: r => r.accessKeys.length ? `${r.accessKeys.filter((k: any) => k.status === 'Active').length} active / ${r.accessKeys.length}` : 'None' }, { key: 'createdAt', label: 'Created', render: r => fmt(r.createdAt) }]} /></Panel>}
    {list === 'roles' && <Panel pad={false}><DataTable rows={Object.values(cloud.iam.roles)} rowKey={r => r.name} onRow={r => nav({ service: 'iam', type: 'role', id: r.name })} placeholder="Find roles" cols={[{ key: 'name', label: 'Role name', render: r => <Link to={{ service: 'iam', type: 'role', id: r.name }}>{r.name}</Link> }, { key: 'trusted', label: 'Trusted entity' }, { key: 'description', label: 'Description' }]} /></Panel>}
    {list === 'policies' && <Panel pad={false}><DataTable rows={Object.entries<any>(cloud.iam.policies).map(([id, p]) => ({ id, ...p }))} rowKey={r => r.id} onRow={r => nav({ service: 'iam', type: 'policy', id: r.id })} placeholder="Find policies" cols={[{ key: 'name', label: 'Policy name', render: r => <Link to={{ service: 'iam', type: 'policy', id: r.id }}>{r.name}</Link> }, { key: 'type', label: 'Type' }, { key: 'used', label: 'Attached entities', render: r => attachedTo(cloud, r.id).length }, { key: 'description', label: 'Description' }]} /></Panel>}
    {list === 'simulator' && <Simulator />}
  </div>;
}
function PolicyLinks({ ids }: { ids: string[] }) { const { cloud } = useLab(); return <Panel title="Permissions policies" pad={false}><DataTable search={false} rows={ids.map(id => ({ id, ...cloud.iam.policies[id] }))} rowKey={r => r.id} empty="No policies attached" cols={[{ key: 'name', label: 'Policy name', render: r => <Link to={{ service: 'iam', type: 'policy', id: r.id }}>{r.name}</Link> }, { key: 'type', label: 'Type' }, { key: 'description', label: 'Description' }]} /></Panel>; }

function IamUser({ u }: { u: any }) {
  const { route, nav, act, busy } = useLab(); const tab = route.tab || 'permissions'; useInspect(`iam/user/${u.name}#${tab}`);
  const toggle = (k: any) => { const status = k.status === 'Active' ? 'Inactive' : 'Active'; act('iam.setAccessKeyStatus', { userName: u.name, accessKeyId: k.id, status }, { confirm: status === 'Inactive' ? { title: `Deactivate ${k.id}?`, body: 'Requests signed with this key will be rejected immediately. You can reactivate it later.', impact: `Any workload still using this key will start failing. Last used from ${k.lastUsedIp} (${k.lastUsedService}).`, label: 'Deactivate', danger: true } : { title: `Activate ${k.id}?`, body: 'Requests signed with this key will be accepted again.', label: 'Activate' } }); };
  return <div className="page"><PageHeader crumbs={[{ label: 'IAM', to: 'iam' }, { label: 'Users', to: { service: 'iam', type: 'users' } }, { label: u.name }]} title={u.name} desc={u.arn} actions={<><ReportBtn resource={`iam/user/${u.name}`} /><button className="btn danger" disabled={busy} onClick={() => act('iam.deleteUser', { userName: u.name }, { confirm: { title: `Delete user ${u.name}?`, body: 'This permanently deletes the user, its access keys and its policy attachments.', impact: 'Workloads using this identity will stop working and audit attribution for its past activity becomes harder.', label: 'Delete user', danger: true } })}>Delete</button></>} />
    <Panel title="Summary"><KV items={[['Created', fmt(u.createdAt)], ['Console access', u.console ? 'Enabled' : 'Disabled'], ['MFA', u.mfa ? 'Enabled' : 'Not enabled'], ['Groups', u.groups.join(', ') || '—']]} /></Panel>
    <Tabs value={tab} onChange={x => nav({ ...route, tab: x })} tabs={[{ id: 'permissions', label: 'Permissions' }, { id: 'credentials', label: 'Security credentials' }, { id: 'tags', label: 'Tags' }]} />
    {tab === 'permissions' && <PolicyLinks ids={u.policies} />}
    {tab === 'credentials' && <Panel title="Access keys" pad={false}><DataTable search={false} rows={u.accessKeys} rowKey={r => r.id} empty="No access keys" cols={[{ key: 'id', label: 'Access key ID', render: r => <code>{r.id}</code> }, { key: 'status', label: 'Status', render: r => <Badge tone={r.status === 'Active' ? 'green' : 'grey'}>{r.status}</Badge> }, { key: 'createdAt', label: 'Created', render: r => fmt(r.createdAt) }, { key: 'lastUsed', label: 'Last used', render: r => fmt(r.lastUsed) }, { key: 'lastUsedIp', label: 'Last used from' }, { key: 'lastUsedService', label: 'Service' }, { key: 'a', label: 'Actions', render: r => <button className="btn sm" disabled={busy} onClick={() => toggle(r)}>{r.status === 'Active' ? 'Deactivate' : 'Activate'}</button> }]} /></Panel>}
    {tab === 'tags' && <Panel title="Tags">{Object.keys(u.tags).length ? <KV items={Object.entries<any>(u.tags)} /> : <Empty title="No tags" />}</Panel>}
  </div>;
}
function IamRole({ r }: { r: any }) {
  const { route, nav, act, busy } = useLab(); const tab = route.tab || 'permissions'; useInspect(`iam/role/${r.name}#${tab}`);
  return <div className="page"><PageHeader crumbs={[{ label: 'IAM', to: 'iam' }, { label: 'Roles', to: { service: 'iam', type: 'roles' } }, { label: r.name }]} title={r.name} desc={r.arn} actions={<><ReportBtn resource={`iam/role/${r.name}`} /><button className="btn danger" disabled={busy} onClick={() => act('iam.deleteRole', { roleName: r.name }, { confirm: { title: `Delete role ${r.name}?`, body: 'This permanently deletes the role.', impact: 'Any service assuming this role will lose all access.', label: 'Delete role', danger: true } })}>Delete</button></>} />
    <Panel title="Summary"><KV items={[['Description', r.description || '—'], ['Created', fmt(r.createdAt)], ['Trusted entity', r.trusted]]} /></Panel>
    <Tabs value={tab} onChange={x => nav({ ...route, tab: x })} tabs={[{ id: 'permissions', label: 'Permissions' }, { id: 'trust', label: 'Trust relationships' }]} />
    {tab === 'permissions' ? <PolicyLinks ids={r.policies} /> : <Panel title="Trusted entities"><JsonEditor id="trust" readOnly doc={{ Version: '2012-10-17', Statement: [{ Effect: 'Allow', Principal: r.trusted.startsWith('arn') ? { AWS: r.trusted } : { Service: r.trusted }, Action: 'sts:AssumeRole' }] }} /></Panel>}
  </div>;
}
function IamPolicy({ id, p }: { id: string; p: any }) {
  const { route, nav, act, busy, cloud } = useLab(); const tab = route.tab || 'permissions'; useInspect(`iam/policy/${id}#${tab}`);
  const ents = attachedTo(cloud, id);
  const save = async (text: string) => !!(await act('iam.updatePolicy', { policyId: id, document: text }, { confirm: { title: `Save changes to ${p.name}?`, body: 'A new policy version becomes the default immediately. Previous versions are kept and can be restored.', impact: `Attached to ${ents.map(e => `${e.kind} ${e.name}`).join(', ') || 'no entities'}. Removing a permission a workload needs will break it.`, label: 'Save policy' } }))?.ok;
  return <div className="page"><PageHeader crumbs={[{ label: 'IAM', to: 'iam' }, { label: 'Policies', to: { service: 'iam', type: 'policies' } }, { label: p.name }]} title={p.name} desc={`${p.type} policy · ${p.description}`} actions={<ReportBtn resource={`iam/policy/${id}`} />} />
    <Tabs value={tab} onChange={x => nav({ ...route, tab: x })} tabs={[{ id: 'permissions', label: 'Permissions' }, { id: 'entities', label: `Entities attached (${ents.length})` }, { id: 'versions', label: `Policy versions (${p.versions.length})` }, { id: 'advisor', label: 'Access Advisor' }]} />
    {tab === 'permissions' && <Panel title="Permissions defined in this policy">{p.protected && <Note>{p.type === 'AWS managed' ? 'AWS managed policies cannot be edited.' : 'This policy defines your own permissions in the simulation and is read-only.'}</Note>}<JsonEditor id={`pol-${id}`} doc={p.document} readOnly={p.protected} onSave={save} /></Panel>}
    {tab === 'entities' && <Panel pad={false}><DataTable search={false} rows={ents} rowKey={r => r.name} empty="Not attached to any identity" cols={[{ key: 'name', label: 'Entity', render: r => <Link to={{ service: 'iam', type: r.kind, id: r.name }}>{r.name}</Link> }, { key: 'kind', label: 'Type' }]} /></Panel>}
    {tab === 'versions' && <Panel pad={false}><DataTable search={false} rows={[...p.versions].reverse()} rowKey={r => r.id} cols={[{ key: 'id', label: 'Version', render: r => <>{r.id} {r.isDefault && <Badge tone="blue">Default</Badge>}</> }, { key: 'createdAt', label: 'Created', render: r => fmt(r.createdAt) }, { key: 'by', label: 'Created by' }, { key: 'doc', label: 'Statements', render: r => <code className="clip">{JSON.stringify(r.document.Statement).slice(0, 90)}…</code> }, { key: 'a', label: 'Actions', render: r => !r.isDefault && !p.protected ? <button className="btn sm" disabled={busy} onClick={() => act('iam.restorePolicyVersion', { policyId: id, versionId: r.id }, { confirm: { title: `Set ${r.id} as default?`, body: `Permissions revert to version ${r.id} immediately.`, impact: 'Entities attached to this policy change permissions at once.', label: 'Set as default' } })}>Set as default</button> : null }]} /></Panel>}
    {tab === 'advisor' && <Panel title="Access Advisor — observed usage, last 90 days" pad={false}><DataTable search={false} rows={p.observedUsage} rowKey={r => r.action + r.resource} empty="No tracked usage for this policy." cols={[{ key: 'action', label: 'Action used', render: r => <code>{r.action}</code> }, { key: 'resource', label: 'On resource', render: r => <code>{r.resource}</code> }, { key: 'calls', label: 'Calls', render: r => r.calls.toLocaleString('en-IN') }]} /><p className="muted pad">Actions granted by the policy but absent from this list were not used during the tracking period.</p></Panel>}
  </div>;
}
function Simulator() {
  const { cloud, act, busy, status } = useLab(); const ps = principals(cloud);
  const [principal, setP] = useState(ps[0].arn); const [action, setA] = useState('s3:GetObject'); const [resource, setR] = useState('*'); const [res, setRes] = useState<any>(null);
  const resources = ['*', ...Object.keys(cloud.s3.buckets).flatMap(b => [arn.bucket(b), `${arn.bucket(b)}/*`]), ...Object.keys(cloud.kms.keys).map(arn.key), ...Object.keys(cloud.secrets.secrets).map(arn.secret), ...Object.keys(cloud.lambda.functions).map(arn.fn), ...Object.keys(cloud.cloudtrail.trails).map(arn.trail), ...Object.keys(cloud.lambda.functions).map(f => arn.logGroup(`/aws/lambda/${f}`))];
  const actions = ['s3:GetObject', 's3:PutObject', 's3:ListBucket', 's3:DeleteObject', 's3:PutBucketPolicy', 'iam:CreateUser', 'iam:CreateAccessKey', 'iam:PassRole', 'iam:CreatePolicyVersion', 'cloudtrail:StopLogging', 'cloudtrail:DeleteTrail', 'cloudtrail:StartLogging', 'lambda:GetFunctionConfiguration', 'lambda:InvokeFunction', 'secretsmanager:GetSecretValue', 'kms:Decrypt', 'kms:GenerateDataKey', 'logs:PutLogEvents', 'logs:CreateLogStream', 'ec2:AuthorizeSecurityGroupIngress', 'ec2:TerminateInstances', 'dynamodb:DeleteTable'];
  return <><Panel title="Policy simulator"><p className="muted">Evaluates identity-based policies and organization guardrails for a principal. Resource policies (bucket and key policies) are evaluated by the S3 access test and the KMS cryptographic test.</p>
    <div className="formrow"><Field label="Principal"><select value={principal} onChange={e => setP(e.target.value)}>{ps.map(p => <option key={p.arn} value={p.arn}>{p.label}</option>)}</select></Field>
      <Field label="Action"><input list="sim-actions" value={action} onChange={e => setA(e.target.value)} /><datalist id="sim-actions">{actions.map(a => <option key={a} value={a} />)}</datalist></Field>
      <Field label="Resource ARN"><input list="sim-res" value={resource} onChange={e => setR(e.target.value)} /><datalist id="sim-res">{resources.map(a => <option key={a} value={a} />)}</datalist></Field>
      <button className="btn primary" disabled={busy} onClick={async () => setRes(await act('iam.simulate', { principal, action: action.trim(), resource: resource.trim() }, { silent: true }))}>Run simulation</button></div>
    <Result r={res} /></Panel>
    <Panel title="Recent simulations" pad={false}><DataTable search={false} rows={status.tests.filter((t: any) => t.kind === 'iam.simulate')} rowKey={r => r.at + r.action + r.principal + r.resource} empty="No simulations run yet" cols={[{ key: 'principal', label: 'Principal', render: r => short(r.principal) }, { key: 'action', label: 'Action' }, { key: 'resource', label: 'Resource', render: r => <code>{r.resource}</code> }, { key: 'allowed', label: 'Decision', render: r => <Badge tone={r.allowed ? 'green' : 'red'}>{r.allowed ? 'allowed' : 'denied'}</Badge> }, { key: 'reason', label: 'Reason' }]} /></Panel></>;
}

// ============================== S3 ==============================
const isPublic = (b: any) => { const pub = (b.policy?.Statement || []).some((s: any) => s.Effect === 'Allow' && (s.Principal === '*' || [s.Principal?.AWS].flat().includes('*'))); return (pub && !b.blockPublicAccess.restrictPublicBuckets) || (b.objects.some((o: any) => o.acl === 'public-read') && !b.blockPublicAccess.ignorePublicAcls); };
const encLabel = (m: string, cloud: any, keyId?: string) => m === 'None' ? 'Not encrypted' : m === 'SSE-KMS' ? `SSE-KMS (${cloud.kms.keys[keyId!]?.alias || keyId})` : 'SSE-S3 (Amazon S3 managed keys)';
export function S3Console() {
  const { route, nav, cloud } = useLab(); const b = cloud.s3.buckets[route.id];
  if (route.type === 'bucket' && b) return <Bucket b={b} />;
  return <div className="page"><PageHeader crumbs={[{ label: 'Amazon S3' }, { label: 'Buckets' }]} title="Buckets" desc="Buckets are containers for data stored in S3." />
    <Panel pad={false}><DataTable rows={Object.values(cloud.s3.buckets)} rowKey={r => r.name} onRow={r => nav({ service: 's3', type: 'bucket', id: r.name })} placeholder="Find buckets by name" cols={[{ key: 'name', label: 'Name', render: r => <Link to={{ service: 's3', type: 'bucket', id: r.name }}>{r.name}</Link> }, { key: 'region', label: 'Region', render: () => 'ap-south-1' }, { key: 'access', label: 'Access', render: r => isPublic(r) ? <Badge tone="red">Public</Badge> : <Badge tone="grey">Not public</Badge> }, { key: 'class', label: 'Classification tag', render: r => r.tags.classification }, { key: 'objects', label: 'Objects', render: r => r.objects.length }, { key: 'createdAt', label: 'Created', render: r => fmt(r.createdAt) }]} /></Panel></div>;
}
function Bucket({ b }: { b: any }) {
  const { route, nav, act, busy, cloud } = useLab(); const tab = route.tab || 'objects'; useInspect(`s3/bucket/${b.name}#${tab}`);
  const [obj, setObj] = useState<string | null>(null); const o = b.objects.find((x: any) => x.key === obj);
  return <div className="page"><PageHeader crumbs={[{ label: 'Amazon S3', to: 's3' }, { label: 'Buckets', to: 's3' }, { label: b.name }]} title={<>{b.name} {isPublic(b) && <Badge tone="red">Publicly accessible</Badge>}</>} desc={`ap-south-1 · created ${fmt(b.createdAt)}`} actions={<><ReportBtn resource={`s3/bucket/${b.name}`} /><button className="btn danger" disabled={busy} onClick={() => act('s3.deleteBucket', { bucket: b.name }, { confirm: { title: `Delete bucket ${b.name}?`, body: 'This permanently deletes the bucket and every object in it.', impact: 'Data loss is irreversible, and evidence needed for the investigation would be destroyed.', label: 'Delete bucket', danger: true } })}>Delete</button></>} />
    <Tabs value={tab} onChange={x => nav({ ...route, tab: x })} tabs={[{ id: 'objects', label: `Objects (${b.objects.length})` }, { id: 'properties', label: 'Properties' }, { id: 'permissions', label: 'Permissions' }]} />
    {tab === 'objects' && <div className={o ? 'split' : ''}><Panel pad={false}><DataTable rows={b.objects} rowKey={r => r.key} selected={obj} onRow={r => setObj(r.key)} placeholder="Find objects by prefix" cols={[{ key: 'key', label: 'Name' }, { key: 'size', label: 'Size', render: r => `${(r.size / 1024).toFixed(1)} KB` }, { key: 'encryption', label: 'Encryption', render: r => r.encryption === 'None' ? <Badge tone="orange">None</Badge> : r.encryption }, { key: 'acl', label: 'ACL', render: r => r.acl === 'public-read' ? <Badge tone="red">public-read</Badge> : 'private' }, { key: 'lastModified', label: 'Last modified', render: r => fmt(r.lastModified) }]} /></Panel>
      {o && <Panel title={o.key} actions={<button className="x" aria-label="Close details" onClick={() => setObj(null)}>×</button>}><KV items={[['Size', `${o.size.toLocaleString('en-IN')} bytes`], ['Server-side encryption', encLabel(o.encryption, cloud, o.keyId)], ['Object ACL', o.acl], ['Last modified', fmt(o.lastModified)]]} />
        <h4>Preview (synthetic data)</h4><pre className="preview">{o.preview}</pre>
        <button className="btn" disabled={busy} onClick={() => act('s3.putObjectAcl', { bucket: b.name, key: o.key, acl: o.acl === 'private' ? 'public-read' : 'private' }, { confirm: o.acl === 'private' ? { title: 'Make object public?', body: `Grant public-read on ${o.key}.`, impact: 'Anyone on the internet could read this object unless Block Public Access prevents it.', label: 'Make public', danger: true } : { title: 'Make object private?', body: `Remove the public-read ACL from ${o.key}.`, label: 'Make private' } })}>{o.acl === 'private' ? 'Make public using ACL' : 'Make private'}</button></Panel>}</div>}
    {tab === 'properties' && <BucketProps b={b} />}
    {tab === 'permissions' && <BucketPerms b={b} />}
  </div>;
}
function BucketProps({ b }: { b: any }) {
  const { act, busy, cloud, setDirty } = useLab(); const [mode, setMode] = useState(b.encryption.mode === 'None' ? 'SSE-S3' : b.encryption.mode); const [keyId, setKeyId] = useState(b.encryption.keyId || Object.keys(cloud.kms.keys)[0]); const [edit, setEdit] = useState(false);
  const stale = b.objects.filter((o: any) => o.encryption !== b.encryption.mode || (o.keyId || null) !== b.encryption.keyId).length;
  return <><Panel title="Bucket overview"><KV items={[['Region', 'ap-south-1'], ['Versioning', b.versioning ? 'Enabled' : 'Disabled'], ...Object.entries<any>(b.tags).map(([k, v]) => [`Tag: ${k}`, v] as [string, any])]} /></Panel>
    <Panel title="Default encryption" actions={!edit && <button className="btn" onClick={() => setEdit(true)}>Edit</button>}>
      {!edit ? <KV items={[['Encryption type', b.encryption.mode === 'None' ? <Badge tone="orange">Not configured</Badge> : encLabel(b.encryption.mode, cloud, b.encryption.keyId)], ['Applies to', 'New objects written after the setting is saved']]} /> : <>
        <fieldset className="checks"><legend>Encryption type</legend>
          <label><input type="radio" checked={mode === 'SSE-S3'} onChange={() => { setMode('SSE-S3'); setDirty('enc', true); }} /> SSE-S3 — Amazon S3 managed keys. No separate key permissions; no per-key audit trail.</label>
          <label><input type="radio" checked={mode === 'SSE-KMS'} onChange={() => { setMode('SSE-KMS'); setDirty('enc', true); }} /> SSE-KMS — AWS KMS key. Readers and writers also need permission on the key; key use is audited.</label></fieldset>
        {mode === 'SSE-KMS' && <Field label="AWS KMS key"><select value={keyId} onChange={e => setKeyId(e.target.value)}>{Object.values<any>(cloud.kms.keys).map(k => <option key={k.id} value={k.id}>{k.alias} ({k.id.slice(0, 8)}…)</option>)}</select></Field>}
        <div className="formrow"><button className="btn" onClick={() => { setEdit(false); setDirty('enc', false); }}>Cancel</button><button className="btn primary" disabled={busy} onClick={async () => { const r = await act('s3.putEncryption', { bucket: b.name, mode, keyId: mode === 'SSE-KMS' ? keyId : undefined }, { confirm: { title: 'Change default encryption?', body: `New objects in ${b.name} will be encrypted with ${mode}. Existing objects are not changed.`, impact: mode === 'SSE-KMS' ? 'Every principal that writes or reads objects will also need permission to use the KMS key. Workloads without it will fail.' : undefined, label: 'Save changes' } }); if (r?.ok) { setEdit(false); setDirty('enc', false); } }}>Save changes</button></div></>}</Panel>
    <Panel title="Existing objects" actions={<button className="btn" disabled={busy || b.encryption.mode === 'None'} onClick={() => act('s3.reencryptObjects', { bucket: b.name }, { confirm: { title: 'Re-encrypt existing objects?', body: `Runs a batch copy that re-writes all ${b.objects.length} objects in place using the bucket's default encryption (${b.encryption.mode}).`, impact: 'Objects get a new last-modified time. Readers will need access to the encryption key afterwards.', label: 'Run batch copy' } })}>Re-encrypt existing objects</button>}>
      <p>{b.encryption.mode === 'None' ? 'Configure default encryption first.' : stale ? <><b>{stale} of {b.objects.length}</b> existing object(s) are not stored with the bucket's current default encryption. Changing the default does not re-encrypt objects that already exist.</> : 'All existing objects match the bucket default encryption.'}</p></Panel></>;
}
function BucketPerms({ b }: { b: any }) {
  const { act, busy, cloud, setDirty } = useLab(); const [bpa, setBpa] = useState(b.blockPublicAccess); const [edit, setEdit] = useState(false);
  useEffect(() => { if (!edit) setBpa(b.blockPublicAccess); }, [b.blockPublicAccess, edit]);
  const L: [string, string, string][] = [['blockPublicAcls', 'Block public access granted through new ACLs', 'Rejects requests that would add a public ACL.'], ['ignorePublicAcls', 'Block public access granted through any ACLs', 'Existing public ACLs are ignored when evaluating access.'], ['blockPublicPolicy', 'Block new public bucket policies', 'Rejects bucket policies that grant public access.'], ['restrictPublicBuckets', 'Restrict access through any public bucket policy', 'If the bucket policy is public, only authorized principals in this account are allowed.']];
  return <><Panel title="Block public access (bucket settings)" actions={!edit && <button className="btn" onClick={() => setEdit(true)}>Edit</button>}>
    <fieldset className="checks" disabled={!edit}><legend className="sr">Block public access settings</legend>{L.map(([k, l, h]) => <label key={k}><input type="checkbox" checked={bpa[k]} onChange={e => { setBpa({ ...bpa, [k]: e.target.checked }); setDirty('bpa', true); }} /> <span><b>{l}</b> — {edit ? h : bpa[k] ? 'On' : 'Off'}</span></label>)}</fieldset>
    {edit && <div className="formrow"><button className="btn" onClick={() => { setEdit(false); setDirty('bpa', false); }}>Cancel</button><button className="btn primary" disabled={busy} onClick={async () => { const r = await act('s3.putPublicAccessBlock', { bucket: b.name, config: bpa }, { confirm: { title: 'Update Block Public Access?', body: `Apply these settings to ${b.name}.`, impact: Object.values(bpa).some(Boolean) ? 'Anything that relies on anonymous access to this bucket (public websites, shared links, public images) will stop working.' : 'Turning these off allows public policies and ACLs to take effect.', label: 'Confirm' } }); if (r?.ok) { setEdit(false); setDirty('bpa', false); } }}>Save changes</button></div>}</Panel>
    <Panel title="Bucket policy" actions={b.policy && <button className="btn" disabled={busy} onClick={() => act('s3.putBucketPolicy', { bucket: b.name, document: null }, { confirm: { title: 'Delete bucket policy?', body: `Removes the entire resource policy from ${b.name}.`, impact: 'Any access granted only by this policy — to the public or to other principals — stops immediately.', label: 'Delete policy', danger: true } })}>Delete policy</button>}>
      <JsonEditor id={`bp-${b.name}`} doc={b.policy} emptyLabel="No bucket policy. Access is governed by IAM policies only." onSave={async text => !!(await act('s3.putBucketPolicy', { bucket: b.name, document: text }, { confirm: { title: 'Save bucket policy?', body: `Replace the resource policy on ${b.name}.`, impact: 'Principals named in the policy gain or lose access immediately.', label: 'Save policy' } }))?.ok} /></Panel>
    <AccessTest b={b} /></>;
}
function AccessTest({ b }: { b: any }) {
  const { act, busy, cloud } = useLab(); const ps = principals(cloud);
  const [principal, setP] = useState('anonymous'); const [operation, setOp] = useState('GET'); const [key, setKey] = useState(b.objects[0]?.key || ''); const [ak, setAk] = useState(''); const [res, setRes] = useState<any>(null);
  const user = principal.includes(':user/') ? cloud.iam.users[principal.split('/').pop()!] : null;
  return <Panel title="Access test"><p className="muted">Sends one simulated request to this bucket and shows how it was authorized. Use it to demonstrate exposure and to verify a fix.</p>
    <div className="formrow"><Field label="Requester"><select value={principal} onChange={e => { setP(e.target.value); setAk(''); }}><option value="anonymous">Anonymous (internet, unsigned)</option>{ps.map(p => <option key={p.arn} value={p.arn}>{p.label}</option>)}</select></Field>
      {user && <Field label="Sign with access key"><select value={ak} onChange={e => setAk(e.target.value)}><option value="">(identity only — no specific key)</option>{user.accessKeys.map((k: any) => <option key={k.id} value={k.id}>{k.id} — {k.status}</option>)}</select></Field>}
      <Field label="Operation"><select value={operation} onChange={e => setOp(e.target.value)}><option>GET</option><option>PUT</option></select></Field>
      <Field label="Object key"><input list={`keys-${b.name}`} value={key} onChange={e => setKey(e.target.value)} /><datalist id={`keys-${b.name}`}>{b.objects.map((o: any) => <option key={o.key} value={o.key} />)}</datalist></Field>
      <button className="btn primary" disabled={busy || !key} onClick={async () => setRes(await act('s3.accessTest', { bucket: b.name, principal, operation, key: key.trim(), accessKeyId: ak || undefined }, { silent: true }))}>Send request</button></div>
    <Result r={res} />{res?.result?.allowed && res.result.preview && <pre className="preview">{res.result.preview}</pre>}</Panel>;
}

// ============================== EC2 ==============================
export function Ec2Console() {
  const { route, nav, cloud, act, busy } = useLab(); const t = route.type || 'instances';
  const g = cloud.ec2.securityGroups[route.id]; const [sel, setSel] = useState<string | null>(null);
  if (t === 'sg' && g) return <SecurityGroup g={g} />;
  const list = ['instances', 'sgs', 'lbs'].includes(t) ? t : 'instances'; const i = cloud.ec2.instances[sel || ''];
  const exp = (id: string) => cloud.exposure.find((e: any) => e.target === id)?.ports || [];
  const sgl = (id: string) => <Link to={{ service: 'ec2', type: 'sg', id }}>{cloud.ec2.securityGroups[id].name}</Link>;
  return <div className="page"><PageHeader crumbs={[{ label: 'EC2' }]} title="EC2" desc="Virtual servers, their network exposure and the security groups that control it." />
    <Tabs value={list} onChange={x => nav({ service: 'ec2', type: x })} tabs={[{ id: 'instances', label: 'Instances' }, { id: 'sgs', label: 'Security groups' }, { id: 'lbs', label: 'Load balancers' }]} />
    {list === 'instances' && <div className={i ? 'split' : ''}><Panel pad={false}><DataTable rows={Object.values(cloud.ec2.instances)} rowKey={r => r.id} selected={sel} onRow={r => setSel(r.id)} placeholder="Find instances" cols={[{ key: 'name', label: 'Name' }, { key: 'id', label: 'Instance ID', render: r => <code>{r.id}</code> }, { key: 'state', label: 'State', render: r => <Badge tone="green">{r.state}</Badge> }, { key: 'type', label: 'Type' }, { key: 'publicIp', label: 'Public IPv4', render: r => r.publicIp || '—' }, { key: 'privateIp', label: 'Private IPv4' }, { key: 'sg', label: 'Security groups', render: r => r.securityGroups.map((s: string) => <span key={s}>{sgl(s)} </span>), text: r => r.securityGroups.join(' ') }]} /></Panel>
      {i && <Panel title={i.name} actions={<button className="x" aria-label="Close details" onClick={() => setSel(null)}>×</button>}><KV items={[['Instance ID', <code>{i.id}</code>], ['State', i.state], ['Subnet', `${i.subnet} (${cloud.vpc.subnets.find((s: any) => s.id === i.subnet).public ? 'public' : 'private'})`], ['Public IPv4', i.publicIp || '—'], ['IAM role', i.role ? <Link to={{ service: 'iam', type: 'role', id: i.role }}>{i.role}</Link> : '—'], ['Security groups', i.securityGroups.map((s: string) => <span key={s}>{sgl(s)} </span>)], ['Internet-reachable ports', exp(i.id).length ? <Badge tone="red">{exp(i.id).map((p: number) => `tcp/${p}`).join(', ')}</Badge> : 'None'], ...Object.entries<any>(i.tags).map(([k, v]) => [`Tag: ${k}`, v] as [string, any])]} />
        <div className="formrow"><button className="btn" disabled={busy} onClick={() => act('ec2.stopInstance', { instanceId: i.id }, { confirm: { title: `Stop ${i.name}?`, body: 'The instance will shut down.', impact: 'Production traffic served by this instance will fail until it is started again.', label: 'Stop instance', danger: true } })}>Stop instance</button>
          <button className="btn danger" disabled={busy} onClick={() => act('ec2.terminateInstance', { instanceId: i.id }, { confirm: { title: `Terminate ${i.name}?`, body: 'Termination is permanent. The instance and its volumes are deleted.', impact: 'Production outage, and loss of forensic evidence on the instance.', label: 'Terminate', danger: true } })}>Terminate instance</button></div></Panel>}</div>}
    {list === 'sgs' && <Panel pad={false}><DataTable rows={Object.values(cloud.ec2.securityGroups)} rowKey={r => r.id} onRow={r => nav({ service: 'ec2', type: 'sg', id: r.id })} placeholder="Find security groups" cols={[{ key: 'name', label: 'Name', render: r => <Link to={{ service: 'ec2', type: 'sg', id: r.id }}>{r.name}</Link> }, { key: 'id', label: 'Security group ID', render: r => <code>{r.id}</code> }, { key: 'description', label: 'Description' }, { key: 'in', label: 'Inbound rules', render: r => r.inbound.length }, { key: 'out', label: 'Outbound rules', render: r => r.outbound.length }]} /></Panel>}
    {list === 'lbs' && <Panel pad={false}><DataTable search={false} rows={Object.values(cloud.ec2.loadBalancers)} rowKey={r => r.name} cols={[{ key: 'name', label: 'Name' }, { key: 'scheme', label: 'Scheme' }, { key: 'dns', label: 'DNS name' }, { key: 'sg', label: 'Security groups', render: r => r.securityGroups.map((s: string) => <span key={s}>{sgl(s)} </span>) }, { key: 't', label: 'Targets', render: r => r.targets.map((x: string) => `${cloud.ec2.instances[x].name}:${r.targetPort}`).join(', ') }]} /></Panel>}
  </div>;
}
function SecurityGroup({ g }: { g: any }) {
  const { route, nav, act, busy, cloud, def } = useLab(); const tab = route.tab || 'inbound'; useInspect(`ec2/sg/${g.id}#${tab}`);
  const [form, setForm] = useState<any>(null);
  const used = [...Object.values<any>(cloud.ec2.instances).filter(i => i.securityGroups.includes(g.id)).map(i => ({ kind: 'Instance', name: i.name, id: i.id })), ...Object.values<any>(cloud.ec2.loadBalancers).filter(l => l.securityGroups.includes(g.id)).map(l => ({ kind: 'Load balancer', name: l.name, id: l.name }))];
  const src = (s: string) => s.startsWith('sg-') ? <><code>{s}</code> ({cloud.ec2.securityGroups[s]?.name})</> : s === '0.0.0.0/0' ? <><code>0.0.0.0/0</code> <Badge tone="orange">Anywhere-IPv4</Badge></> : <code>{s}</code>;
  const impact = `Attached to: ${used.map(u => u.name).join(', ') || 'nothing'}. Traffic that matched this rule may be blocked, or newly allowed, immediately.`;
  const submit = async () => { const p = { groupId: g.id, ruleId: form.id, port: Number(form.port), source: form.source.trim(), description: form.description }; const r = await act(form.id ? 'ec2.updateIngressRule' : 'ec2.addIngressRule', p, { confirm: { title: form.id ? 'Save rule changes?' : 'Add inbound rule?', body: `tcp/${p.port} from ${p.source} on ${g.name}.`, impact, label: form.id ? 'Save rule' : 'Add rule' } }); if (r?.ok) setForm(null); };
  return <div className="page"><PageHeader crumbs={[{ label: 'EC2', to: 'ec2' }, { label: 'Security groups', to: { service: 'ec2', type: 'sgs' } }, { label: g.name }]} title={`${g.id} — ${g.name}`} desc={g.description} actions={<ReportBtn resource={`ec2/sg/${g.id}`} />} />
    <Tabs value={tab} onChange={x => nav({ ...route, tab: x })} tabs={[{ id: 'inbound', label: `Inbound rules (${g.inbound.length})` }, { id: 'outbound', label: 'Outbound rules' }, { id: 'associations', label: `Associations (${used.length})` }, { id: 'reachability', label: 'Reachability test' }]} />
    {tab === 'inbound' && <Panel title="Inbound rules" pad={false} actions={<button className="btn" onClick={() => setForm({ port: '', source: '', description: '' })}>Add rule</button>}>
      <DataTable search={false} rows={g.inbound} rowKey={r => r.id} empty="No inbound rules — all inbound traffic is denied" cols={[{ key: 'id', label: 'Rule ID', render: r => <code>{r.id}</code> }, { key: 'protocol', label: 'Protocol', render: () => 'TCP' }, { key: 'port', label: 'Port' }, { key: 'source', label: 'Source', render: r => src(r.source) }, { key: 'description', label: 'Description' }, { key: 'a', label: 'Actions', render: r => <><button className="btn sm" onClick={() => setForm({ ...r })}>Edit</button> <button className="btn sm" disabled={busy} onClick={() => act('ec2.removeIngressRule', { groupId: g.id, ruleId: r.id }, { confirm: { title: 'Delete inbound rule?', body: `Remove tcp/${r.port} from ${r.source} on ${g.name}.`, impact, label: 'Delete rule', danger: true } })}>Delete</button></> }]} /></Panel>}
    {tab === 'outbound' && <Panel pad={false}><DataTable search={false} rows={g.outbound} rowKey={r => r.id} cols={[{ key: 'id', label: 'Rule ID' }, { key: 'protocol', label: 'Protocol', render: () => 'All' }, { key: 'port', label: 'Port range', render: () => 'All' }, { key: 'source', label: 'Destination', render: r => <code>{r.source}</code> }, { key: 'description', label: 'Description' }]} /></Panel>}
    {tab === 'associations' && <Panel pad={false}><DataTable search={false} rows={used} rowKey={r => r.id} empty="Not attached to any resource" cols={[{ key: 'name', label: 'Resource' }, { key: 'kind', label: 'Type' }, { key: 'id', label: 'ID' }]} /></Panel>}
    {tab === 'reachability' && <Reachability />}
    {form && <Modal title={form.id ? `Edit rule ${form.id}` : 'Add inbound rule'} onClose={() => setForm(null)} footer={<><button className="btn" onClick={() => setForm(null)}>Cancel</button><button className="btn primary" disabled={busy || !form.port || !form.source} onClick={submit}>{form.id ? 'Save rule' : 'Add rule'}</button></>}>
      <Field label="Protocol"><input value="TCP" disabled /></Field><Field label="Port"><input type="number" min={1} max={65535} value={form.port} onChange={e => setForm({ ...form, port: e.target.value })} /></Field>
      <Field label="Source" hint="An IPv4 CIDR such as 203.0.113.0/24, or a security group ID"><input list="sg-src" value={form.source} onChange={e => setForm({ ...form, source: e.target.value })} /><datalist id="sg-src">{Object.values<any>(cloud.ec2.securityGroups).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}<option value="203.0.113.0/24">Office VPN</option><option value="0.0.0.0/0">Anywhere</option></datalist></Field>
      <Field label="Description"><input value={form.description || ''} maxLength={80} onChange={e => setForm({ ...form, description: e.target.value })} /></Field></Modal>}
  </div>;
}
export function Reachability() {
  const { cloud, act, busy, def } = useLab(); const [source, setS] = useState('internet'); const [target, setT] = useState(Object.keys(cloud.ec2.instances)[0]); const [port, setPort] = useState('22'); const [res, setRes] = useState<any>(null);
  return <Panel title="Reachability test"><p className="muted">Attempts one simulated TCP connection and evaluates it against routing and security group rules.</p>
    <div className="formrow"><Field label="Source"><select value={source} onChange={e => setS(e.target.value)}>{def.sources.map((s: any) => <option key={s.id} value={s.id}>{s.label}</option>)}</select></Field>
      <Field label="Destination"><select value={target} onChange={e => setT(e.target.value)}><option value="alb">nc-storefront-alb</option>{Object.values<any>(cloud.ec2.instances).map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select></Field>
      <Field label="TCP port"><input type="number" min={1} max={65535} value={port} onChange={e => setPort(e.target.value)} /></Field>
      <button className="btn primary" disabled={busy || !port} onClick={async () => setRes(await act('ec2.reachabilityTest', { source, target, port: Number(port) }, { silent: true }))}>Run test</button></div><Result r={res} /></Panel>;
}

// ============================== VPC ==============================
export function VpcConsole() {
  const { cloud, route, nav } = useLab(); const tab = route.tab || 'map'; useInspect(`vpc/vpc/${cloud.vpc.id}#${tab}`);
  const app = Object.values<any>(cloud.ec2.instances).find(i => i.name === 'nc-app-server'), batch = Object.values<any>(cloud.ec2.instances).find(i => i.name === 'nc-batch-worker');
  const ports = (id: string) => cloud.exposure.find((e: any) => e.target === id)?.ports || []; const ap = ports(app.id);
  return <div className="page"><PageHeader crumbs={[{ label: 'VPC' }, { label: cloud.vpc.name }]} title={cloud.vpc.name} desc={`${cloud.vpc.id} · ${cloud.vpc.cidr} · internet gateway ${cloud.vpc.igw}`} />
    <Tabs value={tab} onChange={x => nav({ service: 'vpc', tab: x })} tabs={[{ id: 'map', label: 'Resource map' }, { id: 'subnets', label: 'Subnets' }, { id: 'routes', label: 'Route tables' }, { id: 'reachability', label: 'Reachability test' }]} />
    {tab === 'map' && <Panel title="Network exposure map"><p className="muted">Red paths are connections the internet can currently open, computed from live security group rules.</p>
      <svg className="vpcmap" viewBox="0 0 860 330" role="img" aria-label={`Network map. Internet can reach the load balancer on 443 and 80${ap.length ? ` and the app server directly on ports ${ap.join(', ')}` : ''}.`}>
        <rect x="150" y="14" width="696" height="302" rx="6" className="vpc" /><text x="162" y="34" className="lbl">VPC {cloud.vpc.cidr}</text>
        <rect x="170" y="48" width="656" height="150" rx="4" className="sub pub" /><text x="182" y="66" className="lbl">public-1a · 10.0.1.0/24 · route 0.0.0.0/0 → {cloud.vpc.igw}</text>
        <rect x="170" y="212" width="656" height="92" rx="4" className="sub prv" /><text x="182" y="230" className="lbl">private-1a · 10.0.11.0/24 · route 0.0.0.0/0 → NAT</text>
        <g className="node"><rect x="14" y="96" width="104" height="54" rx="27" /><text x="66" y="128" textAnchor="middle">Internet</text></g>
        <g className="node"><rect x="250" y="84" width="170" height="54" rx="4" /><text x="335" y="106" textAnchor="middle">nc-storefront-alb</text><text x="335" y="124" textAnchor="middle" className="sm">nc-alb-sg</text></g>
        <g className={`node ${ap.length ? 'exposed' : ''}`}><rect x="590" y="84" width="200" height="72" rx="4" /><text x="690" y="106" textAnchor="middle">nc-app-server</text><text x="690" y="124" textAnchor="middle" className="sm">{app.publicIp} · nc-app-server-sg</text><text x="690" y="142" textAnchor="middle" className="sm">{ap.length ? `${ap.length} port(s) open to internet` : 'no direct internet access'}</text></g>
        <g className="node"><rect x="590" y="236" width="200" height="54" rx="4" /><text x="690" y="258" textAnchor="middle">nc-batch-worker</text><text x="690" y="276" textAnchor="middle" className="sm">{ports(batch.id).length ? 'EXPOSED' : 'no public IP · nc-internal-sg'}</text></g>
        <path d="M118 118 H250" className="edge ok" /><text x="184" y="110" textAnchor="middle" className="sm">443, 80</text>
        <path d="M420 111 H590" className="edge ok" /><text x="505" y="103" textAnchor="middle" className="sm">8080 (from ALB SG)</text>
        {ap.length > 0 && <><path d="M66 150 V180 H690 V156" className="edge bad" /><text x="380" y="174" textAnchor="middle" className="sm bad">direct from 0.0.0.0/0: {ap.map((p: number) => `tcp/${p}`).join(', ')}</text></>}
        <path d="M690 156 V236" className="edge ok" /><text x="700" y="226" className="sm">5432</text>
      </svg>
      <KV items={[['Internet → load balancer', 'tcp/443, tcp/80 (intended: public storefront)'], ['Internet → nc-app-server', ap.length ? <Badge tone="red">{ap.map((p: number) => `tcp/${p}`).join(', ')}</Badge> : <Badge tone="green">No direct path</Badge>], ['Internet → nc-batch-worker', 'No route (private subnet, no public IP)']]} />
      <p><Link to={{ service: 'ec2', type: 'sgs' }}>Manage security groups in EC2</Link></p></Panel>}
    {tab === 'subnets' && <Panel pad={false}><DataTable search={false} rows={cloud.vpc.subnets} rowKey={r => r.id} cols={[{ key: 'name', label: 'Name' }, { key: 'id', label: 'Subnet ID' }, { key: 'cidr', label: 'IPv4 CIDR' }, { key: 'az', label: 'Availability Zone' }, { key: 'public', label: 'Type', render: r => r.public ? 'Public' : 'Private' }, { key: 'routeTable', label: 'Route table' }, { key: 'res', label: 'Instances', render: r => Object.values<any>(cloud.ec2.instances).filter(i => i.subnet === r.id).map(i => i.name).join(', ') || '—' }]} /></Panel>}
    {tab === 'routes' && cloud.vpc.routeTables.map((rt: any) => <Panel key={rt.id} title={`${rt.name} (${rt.id})`} pad={false}><DataTable search={false} rows={rt.routes} rowKey={r => r.destination} cols={[{ key: 'destination', label: 'Destination' }, { key: 'target', label: 'Target' }]} /></Panel>)}
    {tab === 'reachability' && <Reachability />}
  </div>;
}
