import { useEffect, useState } from 'react';
import { api, arn, fmt } from './api';
import { useLab, PageHeader, Panel, Badge, Note, Field, KV, Tabs, Empty, DataTable, JsonEditor, Link, Modal, Spark } from './ui';
import { useInspect, ReportBtn, Result, principals } from './services1';

// ============================== CloudTrail ==============================
export function CloudTrailConsole() {
  const { route, nav, cloud } = useLab(); const t = route.type || 'events'; const trail = cloud.cloudtrail.trails[route.id];
  if (t === 'trail' && trail) return <Trail t={trail} />;
  return <div className="page"><PageHeader crumbs={[{ label: 'CloudTrail' }]} title="CloudTrail" desc="A record of management API activity in the account — when a trail is logging it." />
    <Tabs value={t === 'trails' ? 'trails' : 'events'} onChange={x => nav({ service: 'cloudtrail', type: x })} tabs={[{ id: 'events', label: `Event history (${cloud.cloudtrail.eventCount})` }, { id: 'trails', label: 'Trails' }]} />
    {t === 'trails' ? <Panel pad={false}><DataTable search={false} rows={Object.values(cloud.cloudtrail.trails)} rowKey={r => r.name} onRow={r => nav({ service: 'cloudtrail', type: 'trail', id: r.name })} cols={[{ key: 'name', label: 'Name', render: r => <Link to={{ service: 'cloudtrail', type: 'trail', id: r.name }}>{r.name}</Link> }, { key: 'homeRegion', label: 'Home region' }, { key: 'multiRegion', label: 'Multi-region trail', render: r => r.multiRegion ? 'Yes' : 'No' }, { key: 'bucket', label: 'S3 bucket' }, { key: 'logging', label: 'Status', render: r => r.logging ? <Badge tone="green">Logging</Badge> : <Badge tone="red">Logging off</Badge> }]} /></Panel> : <EventHistory />}
  </div>;
}
function EventHistory() {
  const { session, cloud, act, busy, status } = useLab(); const [q, setQ] = useState(''); const [page, setPage] = useState(1); const [data, setData] = useState<any>(null); const [err, setErr] = useState(''); const [sel, setSel] = useState<any>(null);
  useInspect('cloudtrail/events/all#list');
  const load = () => { let live = true; api(`/sessions/${session.id}/cloudtrail?page=${page}&size=12&q=${encodeURIComponent(q)}`).then(d => { if (live) { setData(d); setErr(''); } }).catch(e => live && setErr(e.message)); return () => { live = false; }; };
  useEffect(load, [page, q, cloud.cloudtrail.eventCount, session.id]);
  const pages = data ? Math.max(1, Math.ceil(data.total / 12)) : 1; const inLocker = sel && status.evidence.some((e: any) => e.id === sel.id);
  return <div className={sel ? 'split' : ''}><Panel pad={false}>
    <div className="dt-bar"><input type="search" aria-label="Filter events" placeholder="Filter by event name, user, access key, source IP, resource…" value={q} onChange={e => { setQ(e.target.value); setPage(1); }} />
      <span className="muted">{data ? `${data.total} events` : ''}</span><span className="pager"><button className="btn sm" disabled={page <= 1} onClick={() => setPage(page - 1)} aria-label="Previous page">‹</button>{page} / {pages}<button className="btn sm" disabled={page >= pages} onClick={() => setPage(page + 1)} aria-label="Next page">›</button></span></div>
    {err ? <div className="pad"><Note tone="bad">{err} <button className="btn sm" onClick={load}>Retry</button></Note></div> : !data ? <div className="spinner" /> : <div className="dt-scroll"><table><thead><tr><th>Event time</th><th>Event name</th><th>User name</th><th>Source IP</th><th>Access key</th><th>Resource</th><th>Region</th><th>Result</th></tr></thead>
      <tbody>{data.rows.map((e: any) => <tr key={e.id} className={`click ${sel?.id === e.id ? 'sel' : ''}`} tabIndex={0} onClick={() => setSel(e)} onKeyDown={k => k.key === 'Enter' && setSel(e)}><td className="nowrap">{fmt(e.time)}</td><td><a href="#" onClick={x => x.preventDefault()}>{e.name}</a></td><td>{e.actor}</td><td>{e.sourceIp}</td><td className="mono">{e.accessKeyId ? `…${e.accessKeyId.slice(-7)}` : '—'}</td><td>{e.resource}</td><td>{e.region}</td><td>{e.outcome === 'Success' ? 'Success' : <Badge tone="orange">{e.outcome}</Badge>}</td></tr>)}
        {!data.rows.length && <tr><td colSpan={8} className="empty">No events match this filter</td></tr>}</tbody></table></div>}
    {Object.values<any>(cloud.cloudtrail.trails).some(t => !t.logging) && <p className="muted pad">No events appear after {fmt(Object.values<any>(cloud.cloudtrail.trails)[0].stoppedAt)} unless a trail is logging. Activity that was not recorded cannot be recovered later.</p>}</Panel>
    {sel && <Panel title={`${sel.name} · ${sel.id}`} actions={<button className="x" aria-label="Close details" onClick={() => setSel(null)}>×</button>}>
      <KV items={[['Event time', fmt(sel.time)], ['Event source', `${sel.source}.amazonaws.com`], ['User name', sel.actor], ['Access key ID', sel.accessKeyId ? <code>{sel.accessKeyId}</code> : '—'], ['Source IP address', sel.sourceIp], ['User agent', sel.userAgent], ['Resource', sel.resource], ['AWS region', sel.region], ['Read-only', String(sel.readOnly)], ['Result', sel.outcome]]} />
      <button className="btn primary" disabled={busy || inLocker} onClick={() => act('evidence.add', { eventId: sel.id })}>{inLocker ? 'In evidence locker' : 'Add to evidence locker'}</button></Panel>}</div>;
}
function Trail({ t }: { t: any }) {
  const { route, nav, act, busy, setDirty } = useLab(); const tab = route.tab || 'configuration'; useInspect(`cloudtrail/trail/${t.name}#${tab}`);
  const [f, setF] = useState({ multiRegion: t.multiRegion, managementEvents: t.managementEvents, logFileValidation: t.logFileValidation }); const [edit, setEdit] = useState(false); const [res, setRes] = useState<any>(null);
  useEffect(() => { if (!edit) setF({ multiRegion: t.multiRegion, managementEvents: t.managementEvents, logFileValidation: t.logFileValidation }); }, [t, edit]);
  const set = (k: string, v: any) => { setF({ ...f, [k]: v }); setDirty('trail', true); };
  return <div className="page"><PageHeader crumbs={[{ label: 'CloudTrail', to: 'cloudtrail' }, { label: 'Trails', to: { service: 'cloudtrail', type: 'trails' } }, { label: t.name }]} title={<>{t.name} {t.logging ? <Badge tone="green">Logging</Badge> : <Badge tone="red">Logging off</Badge>}</>} desc={`Delivers to s3://${t.bucket}`}
    actions={<><ReportBtn resource={`cloudtrail/trail/${t.name}`} />{t.logging ? <button className="btn" disabled={busy} onClick={() => act('cloudtrail.stopLogging', { name: t.name }, { confirm: { title: 'Stop logging?', body: 'CloudTrail will stop recording events for this trail.', impact: 'Activity during the gap is never recorded and cannot be reconstructed.', label: 'Stop logging', danger: true } })}>Stop logging</button> : <button className="btn primary" disabled={busy} onClick={() => act('cloudtrail.startLogging', { name: t.name }, { confirm: { title: 'Start logging?', body: `Resume recording on ${t.name} with its current configuration.`, label: 'Start logging' } })}>Start logging</button>}
      <button className="btn danger" disabled={busy} onClick={() => act('cloudtrail.deleteTrail', { name: t.name }, { confirm: { title: `Delete ${t.name}?`, body: 'Deletes the trail configuration.', impact: 'The account would have no audit trail.', label: 'Delete trail', danger: true } })}>Delete</button></>} />
    <Tabs value={tab} onChange={x => nav({ ...route, tab: x })} tabs={[{ id: 'configuration', label: 'Configuration' }, { id: 'test', label: 'Audit coverage test' }]} />
    {tab === 'configuration' && <><Panel title="General details"><KV items={[['Trail logging', t.logging ? `Logging${t.startedAt ? ` since ${fmt(t.startedAt)}` : ''}` : `Off — stopped ${fmt(t.stoppedAt)} by ${t.stoppedBy}`], ['Home region', t.homeRegion], ['Log location', `s3://${t.bucket}`]]} /></Panel>
      <Panel title="Coverage" actions={!edit && <button className="btn" onClick={() => setEdit(true)}>Edit</button>}>
        <fieldset className="checks" disabled={!edit}><legend className="sr">Trail coverage</legend>
          <label><input type="checkbox" checked={f.multiRegion} onChange={e => set('multiRegion', e.target.checked)} /> <span><b>Multi-region trail</b> — record events from all regions, not only {t.homeRegion}</span></label>
          <label><input type="checkbox" checked={f.logFileValidation} onChange={e => set('logFileValidation', e.target.checked)} /> <span><b>Log file validation</b> — detect modified or deleted log files</span></label></fieldset>
        <Field label="Management events — API activity to record"><select disabled={!edit} value={f.managementEvents} onChange={e => set('managementEvents', e.target.value)}><option value="All">Read and Write (All)</option><option value="ReadOnly">Read only</option><option value="WriteOnly">Write only</option></select></Field>
        {edit && <div className="formrow"><button className="btn" onClick={() => { setEdit(false); setDirty('trail', false); }}>Cancel</button><button className="btn primary" disabled={busy} onClick={async () => { const r = await act('cloudtrail.updateTrail', { name: t.name, ...f }, { confirm: { title: 'Save trail configuration?', body: `Update coverage settings for ${t.name}.`, label: 'Save changes' } }); if (r?.ok) { setEdit(false); setDirty('trail', false); } }}>Save changes</button></div>}</Panel></>}
    {tab === 'test' && <Panel title="Audit coverage test"><p>Performs one harmless synthetic <b>write</b> call (<code>ec2:CreateTags</code>) in <b>us-east-1</b> and reports whether any trail captured it. If it was captured, find it in Event history.</p>
      <button className="btn primary" disabled={busy} onClick={async () => setRes(await act('cloudtrail.auditTest', {}, { silent: true }))}>Generate synthetic event</button><Result r={res} /></Panel>}
  </div>;
}

// ============================== CloudWatch ==============================
export function CloudWatchConsole() {
  const { route, nav, cloud, act, busy } = useLab(); const cw = cloud.cloudwatch; const t = ['alarms', 'metrics', 'logs', 'notifications'].includes(route.type) ? route.type : route.type === 'log' ? 'logs' : 'alarms';
  useInspect(t === 'alarms' ? 'cloudwatch/alarms/all#list' : `cloudwatch/${t}/all#list`);
  const [form, setForm] = useState<any>(null); const [metric, setMetric] = useState('UnauthorizedAPICalls'); const [count, setCount] = useState('8'); const [res, setRes] = useState<any>(null);
  const tone = (s: string) => s === 'ALARM' ? 'red' : s === 'OK' ? 'green' : 'grey';
  const save = async () => { const r = await act('cloudwatch.putAlarm', { ...form, threshold: Number(form.threshold), period: Number(form.period), topic: form.topic || null }); if (r?.ok) setForm(null); };
  return <div className="page"><PageHeader crumbs={[{ label: 'CloudWatch' }]} title="CloudWatch" desc="Metrics, logs and the alarms that turn them into notifications." actions={t === 'alarms' && <ReportBtn resource="cloudwatch/alarms/all" />} />
    <Tabs value={t} onChange={x => nav({ service: 'cloudwatch', type: x })} tabs={[{ id: 'alarms', label: `Alarms (${Object.keys(cw.alarms).length})` }, { id: 'metrics', label: 'Metrics' }, { id: 'logs', label: 'Log groups' }, { id: 'notifications', label: `Notifications (${cw.notifications.length})` }]} />
    {t === 'alarms' && <><Panel title="Dashboard"><div className="tiles">{['ALARM', 'OK', 'INSUFFICIENT_DATA'].map(s => <div key={s} className="tile"><b>{Object.values<any>(cw.alarms).filter(a => a.state === s).length}</b><Badge tone={tone(s)}>{s.replace('_', ' ')}</Badge></div>)}<div className="tile"><b>{cw.metricDefs.length}</b><span>metrics available</span></div></div></Panel>
      <Panel title="Alarms" pad={false} actions={<button className="btn primary" onClick={() => setForm({ name: '', metric: cw.metricDefs[0].name, comparison: '>=', threshold: '', period: 300, topic: '' })}>Create alarm</button>}>
      <DataTable search={false} rows={Object.values(cw.alarms)} rowKey={r => r.name} empty="No alarms" cols={[{ key: 'name', label: 'Name' }, { key: 'state', label: 'State', render: r => <Badge tone={tone(r.state)}>{r.state.replace('_', ' ')}</Badge> }, { key: 'cond', label: 'Condition', render: r => <code>{r.metric} {r.comparison} {r.threshold} / {r.period}s</code> }, { key: 'topic', label: 'Notify', render: r => r.topic || <span className="muted">no action</span> }, { key: 'createdBy', label: 'Created by' }, { key: 'a', label: 'Actions', render: r => <><button className="btn sm" onClick={() => setForm({ ...r, topic: r.topic || '' })}>Edit</button> <button className="btn sm" disabled={busy} onClick={() => act('cloudwatch.deleteAlarm', { name: r.name }, { confirm: { title: `Delete alarm ${r.name}?`, body: 'The alarm and its history are removed.', impact: 'Whoever relies on this notification will no longer be alerted.', label: 'Delete alarm', danger: true } })}>Delete</button></> }]} /></Panel></>}
    {t === 'metrics' && <><Panel title="Metrics" pad={false}><DataTable search={false} rows={cw.metricDefs} rowKey={r => r.name} cols={[{ key: 'namespace', label: 'Namespace' }, { key: 'name', label: 'Metric' }, { key: 'description', label: 'Description' }, { key: 'source', label: 'Fed by', render: r => r.source === 'cloudtrail' ? 'CloudTrail log metric filter' : 'Agent / service' }, { key: 'd', label: 'Recent datapoints', render: r => <Spark points={cw.metrics[r.name]} threshold={Object.values<any>(cw.alarms).find(a => a.metric === r.name)?.threshold} /> }, { key: 'al', label: 'Alarms', render: r => Object.values<any>(cw.alarms).filter(a => a.metric === r.name).map(a => a.name).join(', ') || <span className="muted">none</span> }]} /></Panel>
      <Panel title="Generate test events"><p className="muted">Publishes deterministic synthetic events for one evaluation period, then evaluates every alarm on that metric.</p>
        <div className="formrow"><Field label="Metric"><select value={metric} onChange={e => setMetric(e.target.value)}>{cw.metricDefs.map((m: any) => <option key={m.name}>{m.name}</option>)}</select></Field><Field label="Number of events in the period"><input type="number" min={1} max={100} value={count} onChange={e => setCount(e.target.value)} /></Field>
          <button className="btn primary" disabled={busy || !count} onClick={async () => setRes(await act('cloudwatch.sendTestEvents', { metric, count: Number(count) }, { silent: true }))}>Send test events</button></div><Result r={res} /></Panel></>}
    {t === 'logs' && <Logs />}
    {t === 'notifications' && <Panel title="Delivered notifications (simulated SNS)" pad={false}><DataTable search={false} rows={[...cw.notifications].reverse()} rowKey={r => r.at + r.alarm + r.message} empty="No notifications delivered" cols={[{ key: 'at', label: 'Time', render: r => fmt(r.at) }, { key: 'topic', label: 'Topic' }, { key: 'alarm', label: 'Alarm' }, { key: 'message', label: 'Message' }]} /><p className="muted pad">Topics: {cw.topics.join(', ')}</p></Panel>}
    {form && <Modal title={cw.alarms[form.name] ? `Edit alarm ${form.name}` : 'Create alarm'} onClose={() => setForm(null)} footer={<><button className="btn" onClick={() => setForm(null)}>Cancel</button><button className="btn primary" disabled={busy || !form.name || form.threshold === ''} onClick={save}>Save alarm</button></>}>
      <Field label="Alarm name" hint="Letters, numbers, hyphens and underscores"><input value={form.name} disabled={!!cw.alarms[form.name] && form.createdBy} onChange={e => setForm({ ...form, name: e.target.value })} /></Field>
      <Field label="Metric"><select value={form.metric} onChange={e => setForm({ ...form, metric: e.target.value })}>{cw.metricDefs.map((m: any) => <option key={m.name} value={m.name}>{m.namespace} · {m.name}</option>)}</select></Field>
      <div className="formrow"><Field label="Whenever the value is"><select value={form.comparison} onChange={e => setForm({ ...form, comparison: e.target.value })}>{['>=', '>', '<=', '<'].map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Threshold"><input type="number" min={0} value={form.threshold} onChange={e => setForm({ ...form, threshold: e.target.value })} /></Field><Field label="Period"><select value={form.period} onChange={e => setForm({ ...form, period: e.target.value })}><option value={60}>1 minute</option><option value={300}>5 minutes</option><option value={900}>15 minutes</option></select></Field></div>
      <Field label="Notification" hint="Where the alarm sends a message when it enters ALARM"><select value={form.topic} onChange={e => setForm({ ...form, topic: e.target.value })}><option value="">No notification</option>{cw.topics.map((x: string) => <option key={x}>{x}</option>)}</select></Field></Modal>}
  </div>;
}
function Logs() {
  const { route, nav, cloud } = useLab(); const groups = cloud.cloudwatch.logGroups; const g = route.type === 'log' ? groups[route.id] : null; const stream = g && route.tab && g.streams[route.tab] ? route.tab : null;
  useInspect(stream ? `cloudwatch/log/${route.id}/${stream}#events` : null);
  if (!g) return <Panel pad={false}><DataTable rows={Object.entries<any>(groups).map(([name, v]) => ({ name, n: Object.keys(v.streams).length }))} rowKey={r => r.name} onRow={r => nav({ service: 'cloudwatch', type: 'log', id: r.name })} placeholder="Find log groups" cols={[{ key: 'name', label: 'Log group', render: r => <Link to={{ service: 'cloudwatch', type: 'log', id: r.name }}>{r.name}</Link> }, { key: 'n', label: 'Streams' }]} /></Panel>;
  return <div className="split"><Panel title={<><Link to={{ service: 'cloudwatch', type: 'logs' }}>Log groups</Link> › {route.id}</>} pad={false}><DataTable search={false} rows={Object.keys(g.streams).map(s => ({ s, n: g.streams[s].length }))} rowKey={r => r.s} selected={stream} onRow={r => nav({ service: 'cloudwatch', type: 'log', id: route.id, tab: r.s })} cols={[{ key: 's', label: 'Log stream' }, { key: 'n', label: 'Events' }]} /></Panel>
    <Panel title={stream ? `Log events — ${stream}` : 'Log events'}>{stream ? <pre className="logs" tabIndex={0}>{g.streams[stream].join('\n') || 'No events'}</pre> : <Empty title="Select a log stream">Choose a stream to read its events.</Empty>}</Panel></div>;
}

// ============================== Lambda ==============================
export function LambdaConsole() {
  const { route, nav, cloud } = useLab(); const f = cloud.lambda.functions[route.id];
  if (route.type === 'function' && f) return <Fn f={f} />;
  return <div className="page"><PageHeader crumbs={[{ label: 'Lambda' }, { label: 'Functions' }]} title="Functions" desc="Serverless functions and the configuration they run with." />
    <Panel pad={false}><DataTable rows={Object.values(cloud.lambda.functions)} rowKey={r => r.name} onRow={r => nav({ service: 'lambda', type: 'function', id: r.name })} placeholder="Find functions" cols={[{ key: 'name', label: 'Function name', render: r => <Link to={{ service: 'lambda', type: 'function', id: r.name }}>{r.name}</Link> }, { key: 'description', label: 'Description' }, { key: 'runtime', label: 'Runtime' }, { key: 'lastModified', label: 'Last modified', render: r => fmt(r.lastModified) }]} /></Panel></div>;
}
function Fn({ f }: { f: any }) {
  const { route, nav, act, busy, setDirty } = useLab(); const tab = route.tab || 'configuration'; useInspect(`lambda/function/${f.name}#${tab}`);
  const [rows, setRows] = useState<[string, string][] | null>(null); const [res, setRes] = useState<any>(null);
  const edit = (r: [string, string][]) => { setRows(r); setDirty('env', true); };
  const save = async () => { const keys = rows!.map(r => r[0].trim()); if (keys.some(k => !k) || new Set(keys).size !== keys.length) return act('lambda.updateConfig', { name: f.name, env: null }); const r = await act('lambda.updateConfig', { name: f.name, env: Object.fromEntries(rows!.map(([k, v]) => [k.trim(), v])) }, { confirm: { title: 'Save environment variables?', body: `The next invocation of ${f.name} uses the new configuration.`, impact: 'If the function code expects a variable you removed or renamed, invocations will fail.', label: 'Save' } }); if (r?.ok) { setRows(null); setDirty('env', false); } };
  return <div className="page"><PageHeader crumbs={[{ label: 'Lambda', to: 'lambda' }, { label: 'Functions', to: 'lambda' }, { label: f.name }]} title={f.name} desc={f.description} actions={<><ReportBtn resource={`lambda/function/${f.name}`} /><button className="btn danger" disabled={busy} onClick={() => act('lambda.deleteFunction', { name: f.name }, { confirm: { title: `Delete ${f.name}?`, body: 'Permanently deletes the function and its configuration.', impact: 'Order processing stops.', label: 'Delete function', danger: true } })}>Delete</button></>} />
    <Tabs value={tab} onChange={x => nav({ ...route, tab: x })} tabs={[{ id: 'configuration', label: 'Configuration' }, { id: 'test', label: 'Test' }, { id: 'monitor', label: 'Monitor' }]} />
    {tab === 'configuration' && <><Panel title="General configuration"><KV items={[['Runtime', f.runtime], ['Handler', f.handler], ['Memory', `${f.memory} MB`], ['Timeout', `${f.timeout} s`], ['Execution role', <Link to={{ service: 'iam', type: 'role', id: f.role }}>{f.role}</Link>], ['Last modified', fmt(f.lastModified)], ['Function ARN', <code>{arn.fn(f.name)}</code>]]} /></Panel>
      <Panel title="Environment variables" pad={!!rows} actions={!rows && <button className="btn" onClick={() => setRows(Object.entries(f.env))}>Edit</button>}>
        {!rows ? <DataTable search={false} rows={Object.entries<any>(f.env).map(([k, v]) => ({ k, v }))} rowKey={r => r.k} empty="No environment variables" cols={[{ key: 'k', label: 'Key', render: r => <code>{r.k}</code> }, { key: 'v', label: 'Value', render: r => <code>{r.v}</code> }]} /> : <>
          {rows.map(([k, v], i) => <div key={i} className="envrow"><input aria-label="Key" placeholder="KEY" value={k} onChange={e => edit(rows.map((r, j) => j === i ? [e.target.value, r[1]] : r))} /><input aria-label="Value" placeholder="value" value={v} onChange={e => edit(rows.map((r, j) => j === i ? [r[0], e.target.value] : r))} /><button className="btn sm" onClick={() => edit(rows.filter((_, j) => j !== i))}>Remove</button></div>)}
          <div className="formrow"><button className="btn" onClick={() => edit([...rows, ['', '']])}>Add environment variable</button><span className="grow" /><button className="btn" onClick={() => { setRows(null); setDirty('env', false); }}>Cancel</button><button className="btn primary" disabled={busy} onClick={save}>Save</button></div></>}</Panel></>}
    {tab === 'test' && <Panel title="Test event"><p className="muted">Invokes the function once with a synthetic order batch. The function writes logs, obtains its payment credential, authenticates to the simulated gateway and exports to S3 — each step authorized against its execution role.</p>
      <pre className="preview">{'{ "source": "threatready.test", "orders": 3, "synthetic": true }'}</pre>
      <button className="btn primary" disabled={busy} onClick={async () => setRes(await act('lambda.invoke', { name: f.name }, { silent: true }))}>Test</button><Result r={res} />{res?.result?.logs && <><h4>Execution log</h4><pre className="logs">{res.result.logs.join('\n')}</pre></>}</Panel>}
    {tab === 'monitor' && <Panel title="Recent invocations"><KV items={[['Last test invocation', f.lastInvocation ? `${fmt(f.lastInvocation.at)} — ${f.lastInvocation.ok ? 'succeeded' : `failed: ${f.lastInvocation.error}`}` : 'None in this session']]} /><p><Link to={{ service: 'cloudwatch', type: 'log', id: `/aws/lambda/${f.name}` }}>View logs in CloudWatch</Link> · <Link to={{ service: 'iam', type: 'role', id: f.role }}>View execution role</Link></p></Panel>}
  </div>;
}

// ============================== KMS ==============================
export function KmsConsole() {
  const { route, nav, cloud } = useLab(); const k = cloud.kms.keys[route.id];
  if (route.type === 'key' && k) return <Key k={k} />;
  return <div className="page"><PageHeader crumbs={[{ label: 'KMS' }, { label: 'Customer managed keys' }]} title="Customer managed keys" desc="Encryption keys you control, and the key policies that decide who can use them." />
    <Panel pad={false}><DataTable search={false} rows={Object.values(cloud.kms.keys)} rowKey={r => r.id} onRow={r => nav({ service: 'kms', type: 'key', id: r.id })} cols={[{ key: 'alias', label: 'Alias', render: r => <Link to={{ service: 'kms', type: 'key', id: r.id }}>{r.alias}</Link> }, { key: 'id', label: 'Key ID', render: r => <code>{r.id}</code> }, { key: 'state', label: 'Status', render: r => <Badge tone="green">{r.state}</Badge> }, { key: 'description', label: 'Description' }]} /></Panel></div>;
}
function Key({ k }: { k: any }) {
  const { route, nav, act, busy, cloud } = useLab(); const tab = route.tab || 'policy'; useInspect(`kms/key/${k.id}#${tab}`);
  const ps = principals(cloud); const [principal, setP] = useState(ps[0].arn); const [operation, setOp] = useState('Decrypt'); const [res, setRes] = useState<any>(null);
  const usedBy = Object.values<any>(cloud.s3.buckets).filter(b => b.encryption.keyId === k.id).map(b => b.name);
  return <div className="page"><PageHeader crumbs={[{ label: 'KMS', to: 'kms' }, { label: 'Customer managed keys', to: 'kms' }, { label: k.alias }]} title={k.alias} desc={k.description} actions={<><ReportBtn resource={`kms/key/${k.id}`} /><button className="btn" disabled={busy} onClick={() => act('kms.disableKey', { keyId: k.id }, { confirm: { title: 'Disable key?', body: 'All cryptographic operations with this key will fail.', impact: 'Data encrypted under this key becomes unreadable until it is re-enabled.', label: 'Disable key', danger: true } })}>Disable</button><button className="btn danger" disabled={busy} onClick={() => act('kms.scheduleKeyDeletion', { keyId: k.id }, { confirm: { title: 'Schedule key deletion?', body: 'After the waiting period the key is destroyed.', impact: 'Everything encrypted under this key becomes permanently unrecoverable.', label: 'Schedule deletion', danger: true } })}>Schedule deletion</button></>} />
    <Tabs value={tab} onChange={x => nav({ ...route, tab: x })} tabs={[{ id: 'policy', label: 'Key policy' }, { id: 'test', label: 'Cryptographic test' }, { id: 'general', label: 'General configuration' }]} />
    {tab === 'policy' && <><Panel title="Key policy"><p className="muted">The key policy is the primary access control for this key. IAM policies grant access only if the key policy delegates to IAM through the account root principal. KMS rejects any policy that would leave no administrator able to change it.</p>
      <JsonEditor id={`kp-${k.id}`} doc={k.policy} onSave={async text => !!(await act('kms.putKeyPolicy', { keyId: k.id, document: text }, { confirm: { title: 'Save key policy?', body: `Replace the key policy of ${k.alias}.`, impact: `Principals removed from the policy lose the ability to encrypt or decrypt at once.${usedBy.length ? ` Used for S3 encryption by: ${usedBy.join(', ')}.` : ''}`, label: 'Save policy' } }))?.ok} /></Panel>
      {k.policyHistory.length > 0 && <Panel title="Previous policy versions" pad={false}><DataTable search={false} rows={k.policyHistory.map((h: any, i: number) => ({ ...h, i }))} rowKey={r => String(r.i)} cols={[{ key: 'at', label: 'Replaced at', render: r => fmt(r.at) }, { key: 'd', label: 'Statements', render: r => <code className="clip">{JSON.stringify(r.document.Statement).slice(0, 100)}…</code> }, { key: 'a', label: 'Actions', render: r => <button className="btn sm" disabled={busy} onClick={() => act('kms.restoreKeyPolicy', { keyId: k.id, index: r.i }, { confirm: { title: 'Restore this key policy?', body: 'The selected version replaces the current key policy.', impact: 'Access to the key changes immediately.', label: 'Restore' } })}>Restore</button> }]} /></Panel>}</>}
    {tab === 'test' && <Panel title="Cryptographic test"><p className="muted">Attempts one operation with this key as the chosen principal and shows how the request was authorized.</p>
      <div className="formrow"><Field label="Principal"><select value={principal} onChange={e => setP(e.target.value)}>{ps.map(p => <option key={p.arn} value={p.arn}>{p.label}</option>)}</select></Field><Field label="Operation"><select value={operation} onChange={e => setOp(e.target.value)}><option>Decrypt</option><option>Encrypt</option><option>GenerateDataKey</option></select></Field>
        <button className="btn primary" disabled={busy} onClick={async () => setRes(await act('kms.cryptoTest', { keyId: k.id, principal, operation }, { silent: true }))}>Run operation</button></div><Result r={res} /></Panel>}
    {tab === 'general' && <Panel title="General configuration"><KV items={[['Key ID', <code>{k.id}</code>], ['ARN', <code>{arn.key(k.id)}</code>], ['Status', k.state], ['Automatic rotation', k.rotation ? 'Enabled' : 'Disabled'], ['Created', fmt(k.createdAt)], ['Used for default encryption by', usedBy.join(', ') || 'No buckets']]} /></Panel>}
  </div>;
}

// ============================== Secrets Manager ==============================
function GatewayCheck({ name }: { name?: string }) {
  const { act, busy, cloud } = useLab(); const names = Object.keys(cloud.secrets.secrets); const [source, setSource] = useState(name ? 'secret' : 'leaked'); const [n, setN] = useState(name || names[0]); const [res, setRes] = useState<any>(null);
  return <Panel title="Payment gateway credential check"><p className="muted">Presents a credential to the simulated payment gateway and reports whether it is accepted. Use it to confirm that a rotated credential works and that an exposed one no longer does.</p>
    <div className="formrow"><Field label="Credential to present"><select value={source} onChange={e => setSource(e.target.value)}><option value="secret">Current value of a stored secret</option><option value="leaked">The credential previously exposed in configuration</option></select></Field>
      {source === 'secret' && <Field label="Secret"><select value={n} onChange={e => setN(e.target.value)}>{names.map(x => <option key={x}>{x}</option>)}</select></Field>}
      <button className="btn primary" disabled={busy} onClick={async () => setRes(await act('secrets.testCredential', { source, name: source === 'secret' ? n : undefined }, { silent: true }))}>Test credential</button></div><Result r={res} /></Panel>;
}
export function SecretsConsole() {
  const { route, nav, cloud, act, busy } = useLab(); const s = cloud.secrets.secrets[route.id]; const [form, setForm] = useState<any>(null);
  if (route.type === 'secret' && s) return <Secret s={s} />;
  return <div className="page"><PageHeader crumbs={[{ label: 'Secrets Manager' }, { label: 'Secrets' }]} title="Secrets" desc="Credentials stored encrypted, retrieved by ARN, versioned and audited." actions={<button className="btn primary" onClick={() => setForm({ name: '', value: '', description: '' })}>Store a new secret</button>} />
    <Panel pad={false}><DataTable rows={Object.values(cloud.secrets.secrets)} rowKey={r => r.name} onRow={r => nav({ service: 'secrets', type: 'secret', id: r.name })} placeholder="Find secrets" cols={[{ key: 'name', label: 'Secret name', render: r => <Link to={{ service: 'secrets', type: 'secret', id: r.name }}>{r.name}</Link> }, { key: 'description', label: 'Description' }, { key: 'rotationCount', label: 'Rotations' }, { key: 'createdBy', label: 'Created by' }, { key: 'createdAt', label: 'Created', render: r => fmt(r.createdAt) }]} /></Panel>
    <GatewayCheck />
    {form && <Modal title="Store a new secret" onClose={() => setForm(null)} footer={<><button className="btn" onClick={() => setForm(null)}>Cancel</button><button className="btn primary" disabled={busy || !form.name || !form.value} onClick={async () => { const r = await act('secrets.create', form); if (r?.ok) { setForm(null); nav({ service: 'secrets', type: 'secret', id: form.name }); } }}>Store secret</button></>}>
      <Field label="Secret name" hint="For example novacart/prod/payment-gateway"><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value.trim() })} /></Field>
      <Field label="Secret value" hint="Stored encrypted. Never shown in lists, logs or the activity history."><input type="password" autoComplete="off" value={form.value} onChange={e => setForm({ ...form, value: e.target.value.trim() })} /></Field>
      <Field label="Description"><input value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Field></Modal>}
  </div>;
}
function Secret({ s }: { s: any }) {
  const { act, busy, route } = useLab(); useInspect(`secrets/secret/${s.name}#overview`); const [value, setValue] = useState<string | null>(null); const [nv, setNv] = useState<string | null>(null);
  useEffect(() => setValue(null), [s.versions.length, s.name]);
  return <div className="page"><PageHeader crumbs={[{ label: 'Secrets Manager', to: 'secrets' }, { label: 'Secrets', to: 'secrets' }, { label: s.name }]} title={s.name} desc={s.description || 'No description'} actions={<><button className="btn" disabled={busy} onClick={() => act('secrets.rotate', { name: s.name }, { confirm: { title: 'Rotate secret now?', body: 'The rotation function generates a new credential, registers it with the target service and revokes the previous one.', impact: 'Anything still using a hard-coded copy of the old value will fail authentication. Clients that read this secret by ARN pick up the new version automatically.', label: 'Rotate' } })}>Rotate secret</button>
    <button className="btn danger" disabled={busy} onClick={() => act('secrets.delete', { name: s.name }, { confirm: { title: `Delete ${s.name}?`, body: 'Schedules the secret for deletion.', impact: 'Workloads that read this secret will fail.', label: 'Delete secret', danger: true } })}>Delete</button></>} />
    <Panel title="Secret details"><KV items={[['Secret ARN', <code>{arn.secret(s.name)}</code>], ['Created', `${fmt(s.createdAt)} by ${s.createdBy}`], ['Rotations', String(s.rotationCount)]]} /></Panel>
    <Panel title="Secret value" actions={<><button className="btn" disabled={busy} onClick={async () => { if (value !== null) return setValue(null); const r = await act('secrets.getValue', { name: s.name }, { silent: true }); if (r?.ok) setValue(r.result.value); }}>{value !== null ? 'Hide' : 'Retrieve secret value'}</button><button className="btn" onClick={() => setNv('')}>Set new value</button></>}>
      {value !== null ? <pre className="preview">{value}</pre> : <p className="muted">Hidden. Retrieving the value is an audited operation.</p>}</Panel>
    <Panel title="Versions" pad={false}><DataTable search={false} rows={[...s.versions].reverse()} rowKey={r => r.id} cols={[{ key: 'id', label: 'Version ID' }, { key: 'stage', label: 'Staging label', render: r => <Badge tone={r.stage === 'AWSCURRENT' ? 'green' : 'grey'}>{r.stage}</Badge> }, { key: 'createdAt', label: 'Created', render: r => fmt(r.createdAt) }]} /></Panel>
    <Panel title="Retrieval audit log" pad={false}><DataTable search={false} rows={[...s.accessLog].reverse()} rowKey={r => r.at + r.by} empty="No retrievals recorded in this session" cols={[{ key: 'at', label: 'Time', render: r => fmt(r.at) }, { key: 'by', label: 'Principal' }, { key: 'action', label: 'Action' }]} /></Panel>
    <GatewayCheck name={s.name} />
    {nv !== null && <Modal title="Set a new secret value" onClose={() => setNv(null)} footer={<><button className="btn" onClick={() => setNv(null)}>Cancel</button><button className="btn primary" disabled={busy || !nv} onClick={async () => { const r = await act('secrets.putValue', { name: s.name, value: nv }); if (r?.ok) setNv(null); }}>Save new version</button></>}><Field label="New value" hint="Creates a new version and marks it current. This does not change what the target service accepts."><input type="password" autoComplete="off" value={nv} onChange={e => setNv(e.target.value.trim())} /></Field></Modal>}
  </div>;
}

// ============================== Governance (Organizations) ==============================
export function OrgConsole() {
  const { route, nav, cloud, act, busy } = useLab(); const org = cloud.org; const t = route.type === 'policies' || route.type === 'policy' ? 'policies' : 'structure';
  useInspect(t === 'policies' ? 'org/policies/all#list' : 'org/structure/all#tree');
  const [target, setTarget] = useState(''); const p = route.type === 'policy' ? org.scps[route.id] : null;
  const targets = [{ id: org.rootId, label: `Root (${org.rootId})` }, ...Object.values<any>(org.ous).map(o => ({ id: o.id, label: `OU: ${o.name}` })), ...Object.values<any>(org.accounts).map(a => ({ id: a.id, label: `Account: ${a.name} (${a.id})` }))];
  const tl = (id: string) => targets.find(x => x.id === id)?.label || id; const on = (id: string) => Object.values<any>(org.scps).filter(s => s.attachedTo.includes(id));
  const chips = (id: string) => on(id).map(s => <Badge key={s.id} tone={s.awsManaged ? 'grey' : 'blue'}>{s.name}</Badge>);
  return <div className="page"><PageHeader crumbs={[{ label: 'Governance' }, ...(p ? [{ label: 'Policies', to: { service: 'org', type: 'policies' } }, { label: p.name }] : [])]} title={p ? p.name : 'Organization governance'} desc={p ? p.description : 'Account structure and service control policies (guardrails) for the NovaCart organization.'} actions={t === 'policies' && <ReportBtn resource="org/policies/all" />} />
    {!p && <Tabs value={t} onChange={x => nav({ service: 'org', type: x })} tabs={[{ id: 'structure', label: 'Accounts' }, { id: 'policies', label: 'Service control policies' }]} />}
    {t === 'structure' && <><Panel title="Organization structure"><ul className="tree"><li><b>Root</b> <code>{org.rootId}</code> {chips(org.rootId)}<ul>
      {Object.values<any>(org.accounts).filter(a => a.parent === org.rootId).map(a => <li key={a.id}>Account <b>{a.name}</b> <code>{a.id}</code> {a.id === org.managementAccount && <Badge tone="grey">management account — SCPs do not apply</Badge>} {chips(a.id)}</li>)}
      {Object.values<any>(org.ous).map(o => <li key={o.id}>OU <b>{o.name}</b> <code>{o.id}</code> {chips(o.id)}<ul>{Object.values<any>(org.accounts).filter(a => a.parent === o.id).map(a => <li key={a.id}>Account <b>{a.name}</b> <code>{a.id}</code> {a.id === cloud.account.id && <Badge tone="orange">this account</Badge>} {chips(a.id)}</li>)}</ul></li>)}</ul></li></ul></Panel>
      <Panel title="How access is decided"><p>Three layers apply to every request. <b>Identity policies</b> grant permissions to a user or role. <b>Resource policies</b> (bucket policy, key policy) grant or restrict access on one resource. <b>Service control policies</b> never grant anything: they set the outer limit for every identity in the accounts they are attached to — including administrators. Test the effect with the IAM policy simulator.</p></Panel></>}
    {t === 'policies' && !p && <Panel pad={false}><DataTable search={false} rows={Object.values(org.scps)} rowKey={r => r.id} onRow={r => nav({ service: 'org', type: 'policy', id: r.id })} cols={[{ key: 'name', label: 'Policy name', render: r => <Link to={{ service: 'org', type: 'policy', id: r.id }}>{r.name}</Link> }, { key: 'kind', label: 'Type', render: r => r.awsManaged ? 'AWS managed' : 'Customer managed' }, { key: 'description', label: 'Description' }, { key: 'attachedTo', label: 'Attached to', render: r => r.attachedTo.length ? r.attachedTo.map(tl).join('; ') : <span className="muted">Not attached</span> }]} /></Panel>}
    {p && <><Panel title="Policy document"><JsonEditor id="scp" readOnly doc={p.document} /></Panel>
      <Panel title="Targets" pad={false} actions={<div className="formrow tight"><select aria-label="Attach target" value={target} onChange={e => setTarget(e.target.value)}><option value="">Select a target…</option>{targets.filter(x => !p.attachedTo.includes(x.id)).map(x => <option key={x.id} value={x.id}>{x.label}</option>)}</select>
        <button className="btn primary" disabled={!target || busy} onClick={async () => { const r = await act('org.attachScp', { scpId: p.id, targetId: target }, { confirm: { title: `Attach ${p.name}?`, body: `Attach to ${tl(target)}.`, impact: 'A deny in a service control policy applies to every user and role in the affected accounts — including administrators and running workloads — and takes effect immediately.', label: 'Attach policy' } }); if (r?.ok) setTarget(''); }}>Attach</button></div>}>
        <DataTable search={false} rows={p.attachedTo.map((id: string) => ({ id }))} rowKey={r => r.id} empty="Not attached to any target" cols={[{ key: 'id', label: 'Target', render: r => tl(r.id) }, { key: 'a', label: 'Actions', render: r => <button className="btn sm" disabled={busy} onClick={() => act('org.detachScp', { scpId: p.id, targetId: r.id }, { confirm: { title: `Detach ${p.name}?`, body: `Detach from ${tl(r.id)}.`, impact: 'Whatever this guardrail prevented becomes possible again for identities with matching IAM permissions.', label: 'Detach policy', danger: true } })}>Detach</button> }]} /></Panel></>}
  </div>;
}
